const creepNumber = [
  {
    role: "harvesterW7N1401",
    bodys: [
      WORK,
      WORK,
      WORK,
      WORK,
      WORK,
      CARRY,
      CARRY,
      CARRY,
      CARRY,
      MOVE,
      MOVE,
      MOVE,
      MOVE,
    ],
  },
  {
    role: "harvesterW7N1402",
    bodys: [
      WORK,
      WORK,
      WORK,
      WORK,
      WORK,
      CARRY,
      CARRY,
      CARRY,
      CARRY,
      MOVE,
      MOVE,
      MOVE,
      MOVE,
    ],
  },
  {
    role: "harvesterW7N1501",
    bodys: [
      WORK,
      WORK,
      WORK,
      WORK,
      WORK,
      WORK,
      WORK,
      CARRY,
      CARRY,
      CARRY,
      CARRY,
      CARRY,
      MOVE,
      MOVE,
      MOVE,
      MOVE,
      MOVE,
    ],
  },
  {
    role: "harvesterW7N1502",
    bodys: [
      WORK,
      WORK,
      WORK,
      WORK,
      WORK,
      WORK,
      WORK,
      CARRY,
      CARRY,
      CARRY,
      CARRY,
      MOVE,
      MOVE,
      MOVE,
      MOVE,
      MOVE,
    ],
  },
  {
    role: "upgraderW7N14",
    bodys: [WORK, CARRY, MOVE],
  },
  {
    role: "upgraderW7N15",
    bodys: [WORK, CARRY, MOVE, WORK, CARRY, MOVE],
  },
  {
    role: "carrierW7N14",
    bodys: [CARRY, CARRY, MOVE, MOVE],
  },
  {
    role: "carrierW7N15",
    bodys: [CARRY, CARRY, MOVE, MOVE, CARRY, CARRY, MOVE, MOVE],
  },
  {
    role: "wallRepairerW7N14",
    bodys: [WORK, CARRY, MOVE],
  },
  {
    role: "wallRepairerW7N15",
    bodys: [WORK, WORK, CARRY, CARRY, MOVE, MOVE],
  },
  {
    role: "terminalTransporterW7N14",
    bodys: [CARRY, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE],
  },
  {
    role: "transporterW7N14",
    bodys: [CARRY, CARRY, CARRY, CARRY, MOVE, MOVE],
  },
  {
    role: "builderW7N15",
    bodys: [WORK, WORK, CARRY, CARRY, MOVE, MOVE],
  },
  {
    role: "builderW7N14",
    bodys: [
      WORK,
      WORK,
      CARRY,
      CARRY,
      MOVE,
      MOVE,
      WORK,
      WORK,
      CARRY,
      CARRY,
      MOVE,
      MOVE,
      WORK,
      WORK,
      CARRY,
      CARRY,
      MOVE,
      MOVE,
      WORK,
      WORK,
      CARRY,
      CARRY,
      MOVE,
      MOVE,
      WORK,
      WORK,
      CARRY,
      CARRY,
      MOVE,
      MOVE,
      WORK,
      WORK,
      CARRY,
      CARRY,
      MOVE,
      MOVE,
    ],
  },
  {
    role: "repairerW7N15",
    bodys: [WORK, WORK, CARRY, CARRY, MOVE, MOVE],
  },
  {
    role: "invader",
    bodys: [
      WORK,
      WORK,
      CARRY,
      CARRY,
      MOVE,
      MOVE,
      WORK,
      WORK,
      CARRY,
      CARRY,
      MOVE,
      MOVE,
    ],
  },
];

module.exports = creepNumber;
